source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'CoreDataHelper_Example', :exclusive => true do
  pod 'CoreDataHelper', :path => '../'
end

target 'CoreDataHelper_Tests', :exclusive => true do
  pod 'CoreDataHelper', :path => '../'

  
end
